### ISSUE TITLE
Deepsource reports incorrect results about loop variable

### ISSUE THREAD

**Issue by jarifibrahim** [deepsourcelabs/cli#13]
This is a bug about the deepsource core system (not the CLI). I couldn't find the correct repository so I've created the issue here. Please move the issue to the correct repository or point me to the correct repository.

We have deepsource enabled on https://github.com/dgraph-io/badger/ and deepsource is running on our CI. Deepsource complains that the loop variable `j` never changes but that's not the case. Here's the line deepsource complains about https://github.com/dgraph-io/badger/blob/be0fe0acd493f0542c90070a5b8ec1ab734d1b44/db_test.go#L2053-L2053

Here's a screenshot of the error
![deepsource](https://user-images.githubusercontent.com/12949454/68673216-31a06b80-0579-11ea-9dce-71aec2564684.png)

**Comment by jarifibrahim** [comment]
hey @jaipradeesh, is this a known issue?

**Comment by jaipradeesh** [comment]
Hi @jarifibrahim Thanks for the report. Taking a look at it. 

That said, the CLI is used to send artifacts from CI systems. Closing this issue. Will leave you an e-mail in a while with the resolution.
