### ISSUE TITLE
Parallel goreleaser builds

### ISSUE THREAD

**Issue by siddhant-deepsource** [deepsourcelabs/cli#150]
As of now, goreleaser builds happen sequentially. Running them in parallel would reduce the release time.

**Comment by burntcarrot** [comment]
@siddhant-deepsource Surprisingly, parallel builds are slower than sequential builds (tested locally):

Parallelism = 8:

```
goreleaser -f ../../goreleaser.yaml -p 8 --skip-validate --snapshot --rm-dist  125.66s user 89.03s system 410% cpu 52.247 total
```

Parallelism = 1:

```
goreleaser -f ../../goreleaser.yaml -p 1 --skip-validate --snapshot --rm-dist  33.62s user 4.26s system 126% cpu 29.901 total
```

I made a test release, and the build times seem to look same after adding parallelism=8, (build time = ~5m): https://github.com/burntcarrot/cli/runs/6824711029?check_suite_focus=true

**Comment by siddhant-deepsource** [comment]
@burntcarrot this is weird. There should be a catch. Will take a look.

**Comment by siddhant-deepsource** [comment]
@burntcarrot Build cache is the catch here. Try running the command with `parallelism` set to 1 after running it with `parallelism` set to 8 and clearing the build cache using this command : ` go clean --cache`. You'll notice the difference.

**Comment by siddhant-deepsource** [comment]
The build cache location can be found using the command `go env GOCACHE`

**Comment by burntcarrot** [comment]
@siddhant-deepsource I did check the cache before experimenting with parallel builds; but even in the Actions workflow, we are having a significant build time. (~5m, after parallel builds)

We might need to reduce some dependencies - cobra and viper are making the binaries bloated. There are other alternatives, some require minimal changes to our existing code. Not against the usage of cobra though.

**Comment by siddhant-deepsource** [comment]
I guess we can replace viper for sure. Replacing cobra is an overkill imo.

**Comment by siddhant-deepsource** [comment]
Still, making the builds parallel would surely reduce some time for now. Not much but can surely give it a try.

**Comment by siddhant-deepsource** [comment]
Not much improvement post adding parallelism. Closing for now.
