### ISSUE TITLE
[feature] Can deepsource have a badge?

### ISSUE THREAD

**Issue by Freed-Wu** [deepsourcelabs/cli#200]
Like <https://shields.io/>. TIA!

**Comment by akshaya-hub** [comment]
@Freed-Wu  Yes, DeepSource provides a badge for your repository that you can display on your README file or your website to show that your code is continuously monitored for quality and security. The badge shows the status of your latest analysis and helps to demonstrate your commitment to producing high-quality code. You can find instructions for adding the badge to your repository on the DeepSource documentation website
