### ISSUE TITLE
DeepSource | Error | .deepsource.toml not found.

### ISSUE THREAD

**Issue by olliephillips** [deepsourcelabs/cli#25]
I've set up DeepSource on a private repo on Github. The `.deepsource.toml` has been configured and added at the root of the repo.  DeepSource reports a few issues on the dashboard. All good.

However, when I try and add code coverage, following the steps to create and pass the `cover.out` report with output from my tests, and having double-checked the syntax and file locations, I still get the above error `DeepSource | Error | .deepsource.toml not found.`

The CI/CD is via Github actions. I'm using Go version 1.13.

**Comment by sauravsrijan** [comment]
@olliephillips can you check if you're running the cli from the root directory?

**Comment by olliephillips** [comment]
Hey @sauravsrijan thanks for checking that - I wasn't. 

I had the implementation code exactly as shown on the DeepSource site, but it turns out I need to cd to the repo, and the call the binary using an absolute path from there.

Would this be mitigated by allowing an OS argument to the path on the CLI - seems like that would be cleaner than having to run from the src directory a call back to the CLI using the absolute path?

But it is running and I have a coverage report on DeepSource now, so thank you for your time in responding.

Closing this.

**Comment by jaipradeesh** [comment]
Appreciate the feedback, @olliephillips Will improve the docs in a couple of days.
