### ISSUE TITLE
cli version in `v0.1.7` is `v0.1.6`

### ISSUE THREAD

**Issue by 06kellyjac** [deepsourcelabs/cli#34]
https://github.com/deepsourcelabs/cli/blob/v0.1.7/constants.go#L4

Also can't overwrite it with ldflags because it's a `const`
https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications

I guess this is related to #28

**Comment by 06kellyjac** [comment]
Still relevant

**Comment by 06kellyjac** [comment]
Still relevant

**Comment by 06kellyjac** [comment]
@siddhant-deepsource

**Comment by siddhant-deepsource** [comment]
Hey @06kellyjac 👋  

Thanks for reporting this. Really sorry for the delay. We will surely push a fix and patch it in the upcoming release.

**Comment by siddhant-deepsource** [comment]
@06kellyjac This has been fixed. Do try out the new `v0.2.0` and share feedback. Its currently in beta and we will be releasing a stable release soon after rigorously testing it. Thanks 😃
